//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestureInteractionServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EXCLUSIVE")]
        public string DEVICE_STATE_EXCLUSIVE {
            get {
                return ((string)(this["DEVICE_STATE_EXCLUSIVE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SHARED")]
        public string DEVICE_STATE_SHARED {
            get {
                return ((string)(this["DEVICE_STATE_SHARED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOT_CONNECTED")]
        public string DEVICE_STATE_NOT_CONNECTED {
            get {
                return ((string)(this["DEVICE_STATE_NOT_CONNECTED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NOT_MANAGED")]
        public string BUS_NOT_MANAGED {
            get {
                return ((string)(this["BUS_NOT_MANAGED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALREADY_ACTIVATED")]
        public string BUS_ALREADY_ACTIVATED {
            get {
                return ((string)(this["BUS_ALREADY_ACTIVATED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ACTIVATED")]
        public string BUS_ACTIVATED {
            get {
                return ((string)(this["BUS_ACTIVATED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEVICES")]
        public string DB_DEVICES_COLLECTION {
            get {
                return ((string)(this["DB_DEVICES_COLLECTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STREAMS")]
        public string DB_STREAMS_COLLECTION {
            get {
                return ((string)(this["DB_STREAMS_COLLECTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GESTURES")]
        public string DB_GESTURES_COLLECTION {
            get {
                return ((string)(this["DB_GESTURES_COLLECTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEPTH")]
        public string DEV_OUTTYPE_DEPTH {
            get {
                return ((string)(this["DEV_OUTTYPE_DEPTH"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RGB")]
        public string DEV_OUTTYPE_RGB {
            get {
                return ((string)(this["DEV_OUTTYPE_RGB"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SKELETON")]
        public string DEV_OUTTYPE_SKELETON {
            get {
                return ((string)(this["DEV_OUTTYPE_SKELETON"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CURSOR")]
        public string DEV_OUTTYPE_CURSOR {
            get {
                return ((string)(this["DEV_OUTTYPE_CURSOR"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STRATEGIES")]
        public string DB_STRATEGIES_COLLECTION {
            get {
                return ((string)(this["DB_STRATEGIES_COLLECTION"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int RECO_WINDOW_SIZE {
            get {
                return ((int)(this["RECO_WINDOW_SIZE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RECO_MINWINDOW_SIZE {
            get {
                return ((int)(this["RECO_MINWINDOW_SIZE"]));
            }
        }
    }
}
